[package]
name = "osc-variant"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["std", "help", "usage", "derive", "error-context"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
quick-xml = { version = "0.28", features = ["escape-html", "serialize"], default-features = false }
xml-rs = "0.8"
console = "0.15"

[profile.release]
opt-level = "s"
codegen-units = 1
lto = "thin"
strip = true
panic = "abort"
